// ----------------------------------------------------------------------------------------
// This file has been automatically generated by a tool and should not be changed manually.
// ----------------------------------------------------------------------------------------
namespace Sirenix.OdinInspector.GeneratedEditors
{
    extern alias Assembly05c96ef9536644ceb53b5c25ce577d3b;
    extern alias Assemblya2264e8eda7840c8954206ccf5ca0bb9;
    extern alias Assemblyd27049463d9e454c859e1c576e1b9407;
    using System.Runtime.CompilerServices;
    using UnityEditor;
    
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::EaAdManager), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_EaAdManager_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::EaAnimation), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_EaAnimation_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::EaCamera), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_EaCamera_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::EaComponent), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_EaComponent_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::EaLeaderboard), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_EaLeaderboard_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::EaListener), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_EaListener_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::EaPhysic), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_EaPhysic_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::EaRotation), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_EaRotation_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::Gravity), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_Gravity_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::Movement), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_Movement_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::PoolManager), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_PoolManager_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::SceneA), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_SceneA_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::SceneB), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_SceneB_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::Ea.EaAdvertisement), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_Ea_EaAdvertisement_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::Ea.EaBanner), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_Ea_EaBanner_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::Ea.EaFile), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_Ea_EaFile_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::Ea.EaInterstitial), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_Ea_EaInterstitial_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::Ea.EaMenu), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_Ea_EaMenu_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::Ea.EaMobile), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_Ea_EaMobile_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::Ea.EaSocial), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_Ea_EaSocial_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::Ea.EaTexture), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_Ea_EaTexture_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::Ea.TEST), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_Ea_TEST_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::GooglePlayGames.OurUtils.PlayGamesHelperObject), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_GooglePlayGames_OurUtils_PlayGamesHelperObject_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::Sirenix.OdinInspector.Demos.AssetListExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_Sirenix_OdinInspector_Demos_AssetListExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::Sirenix.OdinInspector.Demos.BoxGroupExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_Sirenix_OdinInspector_Demos_BoxGroupExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::Sirenix.OdinInspector.Demos.ButtonAndButtonGroupExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_Sirenix_OdinInspector_Demos_ButtonAndButtonGroupExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::Sirenix.OdinInspector.Demos.ColorPaletteExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_Sirenix_OdinInspector_Demos_ColorPaletteExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::Sirenix.OdinInspector.Demos.CombineGroupAttributeExample1), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_Sirenix_OdinInspector_Demos_CombineGroupAttributeExample1_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::Sirenix.OdinInspector.Demos.CombineGroupAttributeExample2), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_Sirenix_OdinInspector_Demos_CombineGroupAttributeExample2_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::Sirenix.OdinInspector.Demos.CombineGroupAttributeExample3), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_Sirenix_OdinInspector_Demos_CombineGroupAttributeExample3_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::Sirenix.OdinInspector.Demos.ContextExample), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_Sirenix_OdinInspector_Demos_ContextExample_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::Sirenix.OdinInspector.Demos.CustomContextMenuExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_Sirenix_OdinInspector_Demos_CustomContextMenuExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::Sirenix.OdinInspector.Demos.CustomDrawerExample), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_Sirenix_OdinInspector_Demos_CustomDrawerExample_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::Sirenix.OdinInspector.Demos.CustomGroupExample), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_Sirenix_OdinInspector_Demos_CustomGroupExample_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::Sirenix.OdinInspector.Demos.DictionaryExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_Sirenix_OdinInspector_Demos_DictionaryExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::Sirenix.OdinInspector.Demos.DisableAndDisabledIfExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_Sirenix_OdinInspector_Demos_DisableAndDisabledIfExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::Sirenix.OdinInspector.Demos.DisableContextMenuExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_Sirenix_OdinInspector_Demos_DisableContextMenuExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::Sirenix.OdinInspector.Demos.DisableInEditorAndPlayModeExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_Sirenix_OdinInspector_Demos_DisableInEditorAndPlayModeExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::Sirenix.OdinInspector.Demos.DisplayAsStringExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_Sirenix_OdinInspector_Demos_DisplayAsStringExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::Sirenix.OdinInspector.Demos.EnumToggleButtonsExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_Sirenix_OdinInspector_Demos_EnumToggleButtonsExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::Sirenix.OdinInspector.Demos.FoldoutGroupAttributeExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_Sirenix_OdinInspector_Demos_FoldoutGroupAttributeExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::Sirenix.OdinInspector.Demos.GenericDrawerExample), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_Sirenix_OdinInspector_Demos_GenericDrawerExample_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::Sirenix.OdinInspector.Demos.GenericMenuExample), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_Sirenix_OdinInspector_Demos_GenericMenuExample_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::Sirenix.OdinInspector.Demos.GUIColorExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_Sirenix_OdinInspector_Demos_GUIColorExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::Sirenix.OdinInspector.Demos.HealthBarExample), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_Sirenix_OdinInspector_Demos_HealthBarExample_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::Sirenix.OdinInspector.Demos.HideInEditorAndPlayModeExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_Sirenix_OdinInspector_Demos_HideInEditorAndPlayModeExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::Sirenix.OdinInspector.Demos.HideLabelExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_Sirenix_OdinInspector_Demos_HideLabelExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::Sirenix.OdinInspector.Demos.HideReferenceObjectPickerExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_Sirenix_OdinInspector_Demos_HideReferenceObjectPickerExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::Sirenix.OdinInspector.Demos.HorizontalGroupAttributeExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_Sirenix_OdinInspector_Demos_HorizontalGroupAttributeExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::Sirenix.OdinInspector.Demos.IncorrectUseOfOdinSerializeAttributeExamples1), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_Sirenix_OdinInspector_Demos_IncorrectUseOfOdinSerializeAttributeExamples1_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::Sirenix.OdinInspector.Demos.IncorrectUseOfOdinSerializeAttributeExamples2), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_Sirenix_OdinInspector_Demos_IncorrectUseOfOdinSerializeAttributeExamples2_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::Sirenix.OdinInspector.Demos.IndentExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_Sirenix_OdinInspector_Demos_IndentExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::Sirenix.OdinInspector.Demos.InfoBoxExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_Sirenix_OdinInspector_Demos_InfoBoxExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::Sirenix.OdinInspector.Demos.InlineEditorExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_Sirenix_OdinInspector_Demos_InlineEditorExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::Sirenix.OdinInspector.Demos.InlinePropertyExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_Sirenix_OdinInspector_Demos_InlinePropertyExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::Sirenix.OdinInspector.Demos.LabelTextExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_Sirenix_OdinInspector_Demos_LabelTextExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::Sirenix.OdinInspector.Demos.ListExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_Sirenix_OdinInspector_Demos_ListExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::Sirenix.OdinInspector.Demos.MinMaxSliderExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_Sirenix_OdinInspector_Demos_MinMaxSliderExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::Sirenix.OdinInspector.Demos.MinMaxValueValueExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_Sirenix_OdinInspector_Demos_MinMaxValueValueExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::Sirenix.OdinInspector.Demos.MultiLinePropertyExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_Sirenix_OdinInspector_Demos_MultiLinePropertyExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::Sirenix.OdinInspector.Demos.NoBoilerplate), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_Sirenix_OdinInspector_Demos_NoBoilerplate_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::Sirenix.OdinInspector.Demos.ObjectPlacer), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_Sirenix_OdinInspector_Demos_ObjectPlacer_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::Sirenix.OdinInspector.Demos.OnInspectorGUIExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_Sirenix_OdinInspector_Demos_OnInspectorGUIExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::Sirenix.OdinInspector.Demos.OnValueChangedExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_Sirenix_OdinInspector_Demos_OnValueChangedExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::Sirenix.OdinInspector.Demos.PlaceableObject), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_Sirenix_OdinInspector_Demos_PlaceableObject_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::Sirenix.OdinInspector.Demos.PrefabRelatedAttributesExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_Sirenix_OdinInspector_Demos_PrefabRelatedAttributesExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::Sirenix.OdinInspector.Demos.PriorityExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_Sirenix_OdinInspector_Demos_PriorityExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::Sirenix.OdinInspector.Demos.PropertyOrderExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_Sirenix_OdinInspector_Demos_PropertyOrderExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::Sirenix.OdinInspector.Demos.PropertyTooltipExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_Sirenix_OdinInspector_Demos_PropertyTooltipExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::Sirenix.OdinInspector.Demos.QuaternionAndVectorExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_Sirenix_OdinInspector_Demos_QuaternionAndVectorExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::Sirenix.OdinInspector.Demos.ReadOnlyExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_Sirenix_OdinInspector_Demos_ReadOnlyExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::Sirenix.OdinInspector.Demos.ReflectionExample), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_Sirenix_OdinInspector_Demos_ReflectionExample_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::Sirenix.OdinInspector.Demos.RequiredExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_Sirenix_OdinInspector_Demos_RequiredExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::Sirenix.OdinInspector.Demos.SceneAndAssetsOnlyExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_Sirenix_OdinInspector_Demos_SceneAndAssetsOnlyExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::Sirenix.OdinInspector.Demos.SerializeAnything), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_Sirenix_OdinInspector_Demos_SerializeAnything_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::Sirenix.OdinInspector.Demos.ShowAndHideIfExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_Sirenix_OdinInspector_Demos_ShowAndHideIfExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::Sirenix.OdinInspector.Demos.ShowInInspectorExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_Sirenix_OdinInspector_Demos_ShowInInspectorExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::Sirenix.OdinInspector.Demos.ShowPropertiesInTheInspectorExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_Sirenix_OdinInspector_Demos_ShowPropertiesInTheInspectorExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::Sirenix.OdinInspector.Demos.StringMemberHelperExample), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_Sirenix_OdinInspector_Demos_StringMemberHelperExample_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::Sirenix.OdinInspector.Demos.TabExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_Sirenix_OdinInspector_Demos_TabExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::Sirenix.OdinInspector.Demos.TitleExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_Sirenix_OdinInspector_Demos_TitleExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::Sirenix.OdinInspector.Demos.TitleGroupExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_Sirenix_OdinInspector_Demos_TitleGroupExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::Sirenix.OdinInspector.Demos.ToggleExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_Sirenix_OdinInspector_Demos_ToggleExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::Sirenix.OdinInspector.Demos.ToggleLeftExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_Sirenix_OdinInspector_Demos_ToggleLeftExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::Sirenix.OdinInspector.Demos.ValidateInputExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_Sirenix_OdinInspector_Demos_ValidateInputExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::Sirenix.OdinInspector.Demos.ValidationExample), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_Sirenix_OdinInspector_Demos_ValidationExample_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::Sirenix.OdinInspector.Demos.ValueDropdownExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_Sirenix_OdinInspector_Demos_ValueDropdownExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly05c96ef9536644ceb53b5c25ce577d3b::Sirenix.OdinInspector.Demos.WrapExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly05c96ef9536644ceb53b5c25ce577d3b_Sirenix_OdinInspector_Demos_WrapExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya2264e8eda7840c8954206ccf5ca0bb9::Sirenix.OdinInspector.Editor.ColorPaletteManager), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya2264e8eda7840c8954206ccf5ca0bb9_Sirenix_OdinInspector_Editor_ColorPaletteManager_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya2264e8eda7840c8954206ccf5ca0bb9::Sirenix.OdinInspector.Editor.GeneralDrawerConfig), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya2264e8eda7840c8954206ccf5ca0bb9_Sirenix_OdinInspector_Editor_GeneralDrawerConfig_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya2264e8eda7840c8954206ccf5ca0bb9::Sirenix.OdinInspector.Editor.InspectorConfig), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya2264e8eda7840c8954206ccf5ca0bb9_Sirenix_OdinInspector_Editor_InspectorConfig_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyd27049463d9e454c859e1c576e1b9407::Sirenix.Serialization.GlobalSerializationConfig), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyd27049463d9e454c859e1c576e1b9407_Sirenix_Serialization_GlobalSerializationConfig_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
}
