// ----------------------------------------------------------------------------------------
// This file has been automatically generated by a tool and should not be changed manually.
// ----------------------------------------------------------------------------------------
namespace Sirenix.OdinInspector.GeneratedEditors
{
    extern alias Assemblya56fe829ab3042b18105925452c1742d;
    extern alias Assemblya2b395989b034e508eedcc6e8518620a;
    extern alias Assemblyce16b33f702b4b69b5cf02a3b6edbed8;
    using System.Runtime.CompilerServices;
    using UnityEditor;
    
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::EaAdManager), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_EaAdManager_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::EaAnimation), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_EaAnimation_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::EaCamera), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_EaCamera_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::EaLeaderboard), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_EaLeaderboard_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::EaListener), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_EaListener_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::EaRotation), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_EaRotation_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::PoolManager), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_PoolManager_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::SceneA), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_SceneA_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::SceneB), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_SceneB_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::Ea.EaAdvertisement), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_Ea_EaAdvertisement_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::Ea.EaBanner), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_Ea_EaBanner_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::Ea.EaFile), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_Ea_EaFile_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::Ea.EaInterstitial), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_Ea_EaInterstitial_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::Ea.EaMenu), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_Ea_EaMenu_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::Ea.EaMobile), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_Ea_EaMobile_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::Ea.EaSocial), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_Ea_EaSocial_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::Ea.EaTexture), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_Ea_EaTexture_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::Ea.TEST), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_Ea_TEST_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::GooglePlayGames.OurUtils.PlayGamesHelperObject), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_GooglePlayGames_OurUtils_PlayGamesHelperObject_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::Sirenix.OdinInspector.Demos.AssetListExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_Sirenix_OdinInspector_Demos_AssetListExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::Sirenix.OdinInspector.Demos.BoxGroupExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_Sirenix_OdinInspector_Demos_BoxGroupExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::Sirenix.OdinInspector.Demos.ButtonAndButtonGroupExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_Sirenix_OdinInspector_Demos_ButtonAndButtonGroupExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::Sirenix.OdinInspector.Demos.ColorPaletteExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_Sirenix_OdinInspector_Demos_ColorPaletteExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::Sirenix.OdinInspector.Demos.CombineGroupAttributeExample1), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_Sirenix_OdinInspector_Demos_CombineGroupAttributeExample1_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::Sirenix.OdinInspector.Demos.CombineGroupAttributeExample2), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_Sirenix_OdinInspector_Demos_CombineGroupAttributeExample2_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::Sirenix.OdinInspector.Demos.CombineGroupAttributeExample3), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_Sirenix_OdinInspector_Demos_CombineGroupAttributeExample3_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::Sirenix.OdinInspector.Demos.ContextExample), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_Sirenix_OdinInspector_Demos_ContextExample_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::Sirenix.OdinInspector.Demos.CustomContextMenuExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_Sirenix_OdinInspector_Demos_CustomContextMenuExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::Sirenix.OdinInspector.Demos.CustomDrawerExample), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_Sirenix_OdinInspector_Demos_CustomDrawerExample_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::Sirenix.OdinInspector.Demos.CustomGroupExample), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_Sirenix_OdinInspector_Demos_CustomGroupExample_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::Sirenix.OdinInspector.Demos.DictionaryExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_Sirenix_OdinInspector_Demos_DictionaryExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::Sirenix.OdinInspector.Demos.DisableAndDisabledIfExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_Sirenix_OdinInspector_Demos_DisableAndDisabledIfExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::Sirenix.OdinInspector.Demos.DisableContextMenuExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_Sirenix_OdinInspector_Demos_DisableContextMenuExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::Sirenix.OdinInspector.Demos.DisableInEditorAndPlayModeExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_Sirenix_OdinInspector_Demos_DisableInEditorAndPlayModeExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::Sirenix.OdinInspector.Demos.DisplayAsStringExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_Sirenix_OdinInspector_Demos_DisplayAsStringExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::Sirenix.OdinInspector.Demos.EnumToggleButtonsExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_Sirenix_OdinInspector_Demos_EnumToggleButtonsExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::Sirenix.OdinInspector.Demos.FoldoutGroupAttributeExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_Sirenix_OdinInspector_Demos_FoldoutGroupAttributeExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::Sirenix.OdinInspector.Demos.GenericDrawerExample), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_Sirenix_OdinInspector_Demos_GenericDrawerExample_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::Sirenix.OdinInspector.Demos.GenericMenuExample), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_Sirenix_OdinInspector_Demos_GenericMenuExample_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::Sirenix.OdinInspector.Demos.GUIColorExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_Sirenix_OdinInspector_Demos_GUIColorExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::Sirenix.OdinInspector.Demos.HealthBarExample), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_Sirenix_OdinInspector_Demos_HealthBarExample_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::Sirenix.OdinInspector.Demos.HideInEditorAndPlayModeExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_Sirenix_OdinInspector_Demos_HideInEditorAndPlayModeExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::Sirenix.OdinInspector.Demos.HideLabelExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_Sirenix_OdinInspector_Demos_HideLabelExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::Sirenix.OdinInspector.Demos.HideReferenceObjectPickerExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_Sirenix_OdinInspector_Demos_HideReferenceObjectPickerExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::Sirenix.OdinInspector.Demos.HorizontalGroupAttributeExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_Sirenix_OdinInspector_Demos_HorizontalGroupAttributeExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::Sirenix.OdinInspector.Demos.IncorrectUseOfOdinSerializeAttributeExamples1), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_Sirenix_OdinInspector_Demos_IncorrectUseOfOdinSerializeAttributeExamples1_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::Sirenix.OdinInspector.Demos.IncorrectUseOfOdinSerializeAttributeExamples2), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_Sirenix_OdinInspector_Demos_IncorrectUseOfOdinSerializeAttributeExamples2_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::Sirenix.OdinInspector.Demos.IndentExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_Sirenix_OdinInspector_Demos_IndentExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::Sirenix.OdinInspector.Demos.InfoBoxExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_Sirenix_OdinInspector_Demos_InfoBoxExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::Sirenix.OdinInspector.Demos.InlineEditorExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_Sirenix_OdinInspector_Demos_InlineEditorExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::Sirenix.OdinInspector.Demos.InlinePropertyExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_Sirenix_OdinInspector_Demos_InlinePropertyExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::Sirenix.OdinInspector.Demos.LabelTextExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_Sirenix_OdinInspector_Demos_LabelTextExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::Sirenix.OdinInspector.Demos.ListExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_Sirenix_OdinInspector_Demos_ListExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::Sirenix.OdinInspector.Demos.MinMaxSliderExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_Sirenix_OdinInspector_Demos_MinMaxSliderExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::Sirenix.OdinInspector.Demos.MinMaxValueValueExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_Sirenix_OdinInspector_Demos_MinMaxValueValueExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::Sirenix.OdinInspector.Demos.MultiLinePropertyExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_Sirenix_OdinInspector_Demos_MultiLinePropertyExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::Sirenix.OdinInspector.Demos.NoBoilerplate), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_Sirenix_OdinInspector_Demos_NoBoilerplate_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::Sirenix.OdinInspector.Demos.ObjectPlacer), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_Sirenix_OdinInspector_Demos_ObjectPlacer_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::Sirenix.OdinInspector.Demos.OnInspectorGUIExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_Sirenix_OdinInspector_Demos_OnInspectorGUIExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::Sirenix.OdinInspector.Demos.OnValueChangedExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_Sirenix_OdinInspector_Demos_OnValueChangedExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::Sirenix.OdinInspector.Demos.PlaceableObject), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_Sirenix_OdinInspector_Demos_PlaceableObject_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::Sirenix.OdinInspector.Demos.PrefabRelatedAttributesExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_Sirenix_OdinInspector_Demos_PrefabRelatedAttributesExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::Sirenix.OdinInspector.Demos.PriorityExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_Sirenix_OdinInspector_Demos_PriorityExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::Sirenix.OdinInspector.Demos.PropertyOrderExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_Sirenix_OdinInspector_Demos_PropertyOrderExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::Sirenix.OdinInspector.Demos.PropertyTooltipExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_Sirenix_OdinInspector_Demos_PropertyTooltipExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::Sirenix.OdinInspector.Demos.QuaternionAndVectorExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_Sirenix_OdinInspector_Demos_QuaternionAndVectorExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::Sirenix.OdinInspector.Demos.ReadOnlyExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_Sirenix_OdinInspector_Demos_ReadOnlyExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::Sirenix.OdinInspector.Demos.ReflectionExample), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_Sirenix_OdinInspector_Demos_ReflectionExample_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::Sirenix.OdinInspector.Demos.RequiredExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_Sirenix_OdinInspector_Demos_RequiredExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::Sirenix.OdinInspector.Demos.SceneAndAssetsOnlyExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_Sirenix_OdinInspector_Demos_SceneAndAssetsOnlyExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::Sirenix.OdinInspector.Demos.SerializeAnything), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_Sirenix_OdinInspector_Demos_SerializeAnything_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::Sirenix.OdinInspector.Demos.ShowAndHideIfExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_Sirenix_OdinInspector_Demos_ShowAndHideIfExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::Sirenix.OdinInspector.Demos.ShowInInspectorExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_Sirenix_OdinInspector_Demos_ShowInInspectorExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::Sirenix.OdinInspector.Demos.ShowPropertiesInTheInspectorExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_Sirenix_OdinInspector_Demos_ShowPropertiesInTheInspectorExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::Sirenix.OdinInspector.Demos.StringMemberHelperExample), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_Sirenix_OdinInspector_Demos_StringMemberHelperExample_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::Sirenix.OdinInspector.Demos.TabExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_Sirenix_OdinInspector_Demos_TabExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::Sirenix.OdinInspector.Demos.TitleExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_Sirenix_OdinInspector_Demos_TitleExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::Sirenix.OdinInspector.Demos.TitleGroupExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_Sirenix_OdinInspector_Demos_TitleGroupExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::Sirenix.OdinInspector.Demos.ToggleExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_Sirenix_OdinInspector_Demos_ToggleExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::Sirenix.OdinInspector.Demos.ToggleLeftExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_Sirenix_OdinInspector_Demos_ToggleLeftExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::Sirenix.OdinInspector.Demos.ValidateInputExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_Sirenix_OdinInspector_Demos_ValidateInputExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::Sirenix.OdinInspector.Demos.ValidationExample), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_Sirenix_OdinInspector_Demos_ValidationExample_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::Sirenix.OdinInspector.Demos.ValueDropdownExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_Sirenix_OdinInspector_Demos_ValueDropdownExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::Sirenix.OdinInspector.Demos.WrapExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_Sirenix_OdinInspector_Demos_WrapExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::UnityStandardAssets.ImageEffects.Antialiasing), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_UnityStandardAssets_ImageEffects_Antialiasing_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::UnityStandardAssets.ImageEffects.Bloom), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_UnityStandardAssets_ImageEffects_Bloom_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::UnityStandardAssets.ImageEffects.BloomAndFlares), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_UnityStandardAssets_ImageEffects_BloomAndFlares_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::UnityStandardAssets.ImageEffects.BloomOptimized), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_UnityStandardAssets_ImageEffects_BloomOptimized_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::UnityStandardAssets.ImageEffects.Blur), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_UnityStandardAssets_ImageEffects_Blur_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::UnityStandardAssets.ImageEffects.BlurOptimized), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_UnityStandardAssets_ImageEffects_BlurOptimized_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::UnityStandardAssets.ImageEffects.CameraMotionBlur), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_UnityStandardAssets_ImageEffects_CameraMotionBlur_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::UnityStandardAssets.ImageEffects.ColorCorrectionCurves), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_UnityStandardAssets_ImageEffects_ColorCorrectionCurves_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::UnityStandardAssets.ImageEffects.ColorCorrectionLookup), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_UnityStandardAssets_ImageEffects_ColorCorrectionLookup_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::UnityStandardAssets.ImageEffects.ColorCorrectionRamp), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_UnityStandardAssets_ImageEffects_ColorCorrectionRamp_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::UnityStandardAssets.ImageEffects.ContrastStretch), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_UnityStandardAssets_ImageEffects_ContrastStretch_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::UnityStandardAssets.ImageEffects.DepthOfField), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_UnityStandardAssets_ImageEffects_DepthOfField_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::UnityStandardAssets.ImageEffects.DepthOfFieldDeprecated), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_UnityStandardAssets_ImageEffects_DepthOfFieldDeprecated_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::UnityStandardAssets.ImageEffects.EdgeDetection), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_UnityStandardAssets_ImageEffects_EdgeDetection_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::UnityStandardAssets.ImageEffects.Fisheye), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_UnityStandardAssets_ImageEffects_Fisheye_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::UnityStandardAssets.ImageEffects.Grayscale), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_UnityStandardAssets_ImageEffects_Grayscale_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::UnityStandardAssets.ImageEffects.ImageEffectBase), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_UnityStandardAssets_ImageEffects_ImageEffectBase_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::UnityStandardAssets.ImageEffects.MotionBlur), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_UnityStandardAssets_ImageEffects_MotionBlur_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::UnityStandardAssets.ImageEffects.NoiseAndGrain), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_UnityStandardAssets_ImageEffects_NoiseAndGrain_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::UnityStandardAssets.ImageEffects.NoiseAndScratches), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_UnityStandardAssets_ImageEffects_NoiseAndScratches_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::UnityStandardAssets.ImageEffects.PostEffectsBase), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_UnityStandardAssets_ImageEffects_PostEffectsBase_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::UnityStandardAssets.ImageEffects.ScreenOverlay), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_UnityStandardAssets_ImageEffects_ScreenOverlay_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::UnityStandardAssets.ImageEffects.ScreenSpaceAmbientOcclusion), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_UnityStandardAssets_ImageEffects_ScreenSpaceAmbientOcclusion_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::UnityStandardAssets.ImageEffects.SepiaTone), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_UnityStandardAssets_ImageEffects_SepiaTone_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::UnityStandardAssets.ImageEffects.SunShafts), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_UnityStandardAssets_ImageEffects_SunShafts_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::UnityStandardAssets.ImageEffects.Tonemapping), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_UnityStandardAssets_ImageEffects_Tonemapping_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::UnityStandardAssets.ImageEffects.Twirl), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_UnityStandardAssets_ImageEffects_Twirl_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::UnityStandardAssets.ImageEffects.VignetteAndChromaticAberration), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_UnityStandardAssets_ImageEffects_VignetteAndChromaticAberration_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya56fe829ab3042b18105925452c1742d::UnityStandardAssets.ImageEffects.Vortex), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya56fe829ab3042b18105925452c1742d_UnityStandardAssets_ImageEffects_Vortex_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya2b395989b034e508eedcc6e8518620a::Sirenix.OdinInspector.Editor.ColorPaletteManager), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya2b395989b034e508eedcc6e8518620a_Sirenix_OdinInspector_Editor_ColorPaletteManager_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya2b395989b034e508eedcc6e8518620a::Sirenix.OdinInspector.Editor.GeneralDrawerConfig), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya2b395989b034e508eedcc6e8518620a_Sirenix_OdinInspector_Editor_GeneralDrawerConfig_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblya2b395989b034e508eedcc6e8518620a::Sirenix.OdinInspector.Editor.InspectorConfig), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblya2b395989b034e508eedcc6e8518620a_Sirenix_OdinInspector_Editor_InspectorConfig_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyce16b33f702b4b69b5cf02a3b6edbed8::Sirenix.Serialization.GlobalSerializationConfig), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyce16b33f702b4b69b5cf02a3b6edbed8_Sirenix_Serialization_GlobalSerializationConfig_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
}
