// ----------------------------------------------------------------------------------------
// This file has been automatically generated by a tool and should not be changed manually.
// ----------------------------------------------------------------------------------------
namespace Sirenix.OdinInspector.GeneratedEditors
{
    extern alias Assembly7bab937f240f4b3eb1090fbc7e25ce83;
    extern alias Assembly9ca0b76bcb564ef1ae1a62cf4e177375;
    extern alias Assembly211d40e70b804a6887cb22caa5d0f790;
    extern alias Assembly97d6cf9292cd44b6913f3f8ceba1f899;
    using System.Runtime.CompilerServices;
    using UnityEditor;
    
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::AnimatorController), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_AnimatorController_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::EaAdManager), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_EaAdManager_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::EaAnimation), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_EaAnimation_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::EaCamera), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_EaCamera_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::EaLeaderboard), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_EaLeaderboard_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::EaListener), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_EaListener_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::EaRotation), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_EaRotation_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly9ca0b76bcb564ef1ae1a62cf4e177375::MouseOrbit), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly9ca0b76bcb564ef1ae1a62cf4e177375_MouseOrbit_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::PoolManager), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_PoolManager_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::SceneA), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_SceneA_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::SceneB), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_SceneB_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::Swapper), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_Swapper_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::Ea.EaAdvertisement), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_Ea_EaAdvertisement_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::Ea.EaBanner), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_Ea_EaBanner_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::Ea.EaFile), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_Ea_EaFile_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::Ea.EaInterstitial), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_Ea_EaInterstitial_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::Ea.EaMenu), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_Ea_EaMenu_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::Ea.EaMobile), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_Ea_EaMobile_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::Ea.EaSocial), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_Ea_EaSocial_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::Ea.EaTexture), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_Ea_EaTexture_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::Ea.TEST), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_Ea_TEST_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::GooglePlayGames.OurUtils.PlayGamesHelperObject), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_GooglePlayGames_OurUtils_PlayGamesHelperObject_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::Sirenix.OdinInspector.Demos.AssetListExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_Sirenix_OdinInspector_Demos_AssetListExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::Sirenix.OdinInspector.Demos.BoxGroupExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_Sirenix_OdinInspector_Demos_BoxGroupExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::Sirenix.OdinInspector.Demos.ButtonAndButtonGroupExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_Sirenix_OdinInspector_Demos_ButtonAndButtonGroupExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::Sirenix.OdinInspector.Demos.ColorPaletteExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_Sirenix_OdinInspector_Demos_ColorPaletteExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::Sirenix.OdinInspector.Demos.CombineGroupAttributeExample1), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_Sirenix_OdinInspector_Demos_CombineGroupAttributeExample1_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::Sirenix.OdinInspector.Demos.CombineGroupAttributeExample2), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_Sirenix_OdinInspector_Demos_CombineGroupAttributeExample2_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::Sirenix.OdinInspector.Demos.CombineGroupAttributeExample3), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_Sirenix_OdinInspector_Demos_CombineGroupAttributeExample3_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::Sirenix.OdinInspector.Demos.ContextExample), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_Sirenix_OdinInspector_Demos_ContextExample_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::Sirenix.OdinInspector.Demos.CustomContextMenuExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_Sirenix_OdinInspector_Demos_CustomContextMenuExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::Sirenix.OdinInspector.Demos.CustomDrawerExample), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_Sirenix_OdinInspector_Demos_CustomDrawerExample_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::Sirenix.OdinInspector.Demos.CustomGroupExample), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_Sirenix_OdinInspector_Demos_CustomGroupExample_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::Sirenix.OdinInspector.Demos.DictionaryExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_Sirenix_OdinInspector_Demos_DictionaryExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::Sirenix.OdinInspector.Demos.DisableAndDisabledIfExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_Sirenix_OdinInspector_Demos_DisableAndDisabledIfExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::Sirenix.OdinInspector.Demos.DisableContextMenuExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_Sirenix_OdinInspector_Demos_DisableContextMenuExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::Sirenix.OdinInspector.Demos.DisableInEditorAndPlayModeExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_Sirenix_OdinInspector_Demos_DisableInEditorAndPlayModeExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::Sirenix.OdinInspector.Demos.DisplayAsStringExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_Sirenix_OdinInspector_Demos_DisplayAsStringExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::Sirenix.OdinInspector.Demos.EnumToggleButtonsExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_Sirenix_OdinInspector_Demos_EnumToggleButtonsExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::Sirenix.OdinInspector.Demos.FoldoutGroupAttributeExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_Sirenix_OdinInspector_Demos_FoldoutGroupAttributeExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::Sirenix.OdinInspector.Demos.GenericDrawerExample), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_Sirenix_OdinInspector_Demos_GenericDrawerExample_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::Sirenix.OdinInspector.Demos.GenericMenuExample), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_Sirenix_OdinInspector_Demos_GenericMenuExample_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::Sirenix.OdinInspector.Demos.GUIColorExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_Sirenix_OdinInspector_Demos_GUIColorExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::Sirenix.OdinInspector.Demos.HealthBarExample), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_Sirenix_OdinInspector_Demos_HealthBarExample_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::Sirenix.OdinInspector.Demos.HideInEditorAndPlayModeExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_Sirenix_OdinInspector_Demos_HideInEditorAndPlayModeExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::Sirenix.OdinInspector.Demos.HideLabelExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_Sirenix_OdinInspector_Demos_HideLabelExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::Sirenix.OdinInspector.Demos.HideReferenceObjectPickerExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_Sirenix_OdinInspector_Demos_HideReferenceObjectPickerExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::Sirenix.OdinInspector.Demos.HorizontalGroupAttributeExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_Sirenix_OdinInspector_Demos_HorizontalGroupAttributeExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::Sirenix.OdinInspector.Demos.IncorrectUseOfOdinSerializeAttributeExamples1), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_Sirenix_OdinInspector_Demos_IncorrectUseOfOdinSerializeAttributeExamples1_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::Sirenix.OdinInspector.Demos.IncorrectUseOfOdinSerializeAttributeExamples2), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_Sirenix_OdinInspector_Demos_IncorrectUseOfOdinSerializeAttributeExamples2_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::Sirenix.OdinInspector.Demos.IndentExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_Sirenix_OdinInspector_Demos_IndentExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::Sirenix.OdinInspector.Demos.InfoBoxExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_Sirenix_OdinInspector_Demos_InfoBoxExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::Sirenix.OdinInspector.Demos.InlineEditorExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_Sirenix_OdinInspector_Demos_InlineEditorExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::Sirenix.OdinInspector.Demos.InlinePropertyExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_Sirenix_OdinInspector_Demos_InlinePropertyExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::Sirenix.OdinInspector.Demos.LabelTextExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_Sirenix_OdinInspector_Demos_LabelTextExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::Sirenix.OdinInspector.Demos.ListExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_Sirenix_OdinInspector_Demos_ListExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::Sirenix.OdinInspector.Demos.MinMaxSliderExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_Sirenix_OdinInspector_Demos_MinMaxSliderExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::Sirenix.OdinInspector.Demos.MinMaxValueValueExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_Sirenix_OdinInspector_Demos_MinMaxValueValueExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::Sirenix.OdinInspector.Demos.MultiLinePropertyExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_Sirenix_OdinInspector_Demos_MultiLinePropertyExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::Sirenix.OdinInspector.Demos.NoBoilerplate), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_Sirenix_OdinInspector_Demos_NoBoilerplate_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::Sirenix.OdinInspector.Demos.ObjectPlacer), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_Sirenix_OdinInspector_Demos_ObjectPlacer_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::Sirenix.OdinInspector.Demos.OnInspectorGUIExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_Sirenix_OdinInspector_Demos_OnInspectorGUIExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::Sirenix.OdinInspector.Demos.OnValueChangedExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_Sirenix_OdinInspector_Demos_OnValueChangedExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::Sirenix.OdinInspector.Demos.PlaceableObject), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_Sirenix_OdinInspector_Demos_PlaceableObject_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::Sirenix.OdinInspector.Demos.PrefabRelatedAttributesExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_Sirenix_OdinInspector_Demos_PrefabRelatedAttributesExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::Sirenix.OdinInspector.Demos.PriorityExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_Sirenix_OdinInspector_Demos_PriorityExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::Sirenix.OdinInspector.Demos.PropertyOrderExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_Sirenix_OdinInspector_Demos_PropertyOrderExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::Sirenix.OdinInspector.Demos.PropertyTooltipExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_Sirenix_OdinInspector_Demos_PropertyTooltipExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::Sirenix.OdinInspector.Demos.QuaternionAndVectorExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_Sirenix_OdinInspector_Demos_QuaternionAndVectorExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::Sirenix.OdinInspector.Demos.ReadOnlyExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_Sirenix_OdinInspector_Demos_ReadOnlyExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::Sirenix.OdinInspector.Demos.ReflectionExample), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_Sirenix_OdinInspector_Demos_ReflectionExample_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::Sirenix.OdinInspector.Demos.RequiredExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_Sirenix_OdinInspector_Demos_RequiredExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::Sirenix.OdinInspector.Demos.SceneAndAssetsOnlyExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_Sirenix_OdinInspector_Demos_SceneAndAssetsOnlyExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::Sirenix.OdinInspector.Demos.SerializeAnything), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_Sirenix_OdinInspector_Demos_SerializeAnything_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::Sirenix.OdinInspector.Demos.ShowAndHideIfExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_Sirenix_OdinInspector_Demos_ShowAndHideIfExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::Sirenix.OdinInspector.Demos.ShowInInspectorExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_Sirenix_OdinInspector_Demos_ShowInInspectorExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::Sirenix.OdinInspector.Demos.ShowPropertiesInTheInspectorExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_Sirenix_OdinInspector_Demos_ShowPropertiesInTheInspectorExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::Sirenix.OdinInspector.Demos.StringMemberHelperExample), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_Sirenix_OdinInspector_Demos_StringMemberHelperExample_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::Sirenix.OdinInspector.Demos.TabExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_Sirenix_OdinInspector_Demos_TabExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::Sirenix.OdinInspector.Demos.TitleExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_Sirenix_OdinInspector_Demos_TitleExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::Sirenix.OdinInspector.Demos.TitleGroupExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_Sirenix_OdinInspector_Demos_TitleGroupExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::Sirenix.OdinInspector.Demos.ToggleExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_Sirenix_OdinInspector_Demos_ToggleExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::Sirenix.OdinInspector.Demos.ToggleLeftExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_Sirenix_OdinInspector_Demos_ToggleLeftExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::Sirenix.OdinInspector.Demos.ValidateInputExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_Sirenix_OdinInspector_Demos_ValidateInputExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::Sirenix.OdinInspector.Demos.ValidationExample), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_Sirenix_OdinInspector_Demos_ValidationExample_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::Sirenix.OdinInspector.Demos.ValueDropdownExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_Sirenix_OdinInspector_Demos_ValueDropdownExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::Sirenix.OdinInspector.Demos.WrapExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_Sirenix_OdinInspector_Demos_WrapExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::UnityStandardAssets.ImageEffects.Antialiasing), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_UnityStandardAssets_ImageEffects_Antialiasing_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::UnityStandardAssets.ImageEffects.Bloom), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_UnityStandardAssets_ImageEffects_Bloom_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::UnityStandardAssets.ImageEffects.BloomAndFlares), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_UnityStandardAssets_ImageEffects_BloomAndFlares_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::UnityStandardAssets.ImageEffects.BloomOptimized), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_UnityStandardAssets_ImageEffects_BloomOptimized_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::UnityStandardAssets.ImageEffects.Blur), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_UnityStandardAssets_ImageEffects_Blur_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::UnityStandardAssets.ImageEffects.BlurOptimized), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_UnityStandardAssets_ImageEffects_BlurOptimized_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::UnityStandardAssets.ImageEffects.CameraMotionBlur), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_UnityStandardAssets_ImageEffects_CameraMotionBlur_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::UnityStandardAssets.ImageEffects.ColorCorrectionCurves), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_UnityStandardAssets_ImageEffects_ColorCorrectionCurves_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::UnityStandardAssets.ImageEffects.ColorCorrectionLookup), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_UnityStandardAssets_ImageEffects_ColorCorrectionLookup_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::UnityStandardAssets.ImageEffects.ColorCorrectionRamp), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_UnityStandardAssets_ImageEffects_ColorCorrectionRamp_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::UnityStandardAssets.ImageEffects.ContrastStretch), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_UnityStandardAssets_ImageEffects_ContrastStretch_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::UnityStandardAssets.ImageEffects.DepthOfField), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_UnityStandardAssets_ImageEffects_DepthOfField_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::UnityStandardAssets.ImageEffects.DepthOfFieldDeprecated), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_UnityStandardAssets_ImageEffects_DepthOfFieldDeprecated_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::UnityStandardAssets.ImageEffects.EdgeDetection), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_UnityStandardAssets_ImageEffects_EdgeDetection_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::UnityStandardAssets.ImageEffects.Fisheye), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_UnityStandardAssets_ImageEffects_Fisheye_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::UnityStandardAssets.ImageEffects.Grayscale), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_UnityStandardAssets_ImageEffects_Grayscale_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::UnityStandardAssets.ImageEffects.ImageEffectBase), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_UnityStandardAssets_ImageEffects_ImageEffectBase_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::UnityStandardAssets.ImageEffects.MotionBlur), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_UnityStandardAssets_ImageEffects_MotionBlur_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::UnityStandardAssets.ImageEffects.NoiseAndGrain), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_UnityStandardAssets_ImageEffects_NoiseAndGrain_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::UnityStandardAssets.ImageEffects.NoiseAndScratches), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_UnityStandardAssets_ImageEffects_NoiseAndScratches_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::UnityStandardAssets.ImageEffects.PostEffectsBase), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_UnityStandardAssets_ImageEffects_PostEffectsBase_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::UnityStandardAssets.ImageEffects.ScreenOverlay), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_UnityStandardAssets_ImageEffects_ScreenOverlay_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::UnityStandardAssets.ImageEffects.ScreenSpaceAmbientOcclusion), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_UnityStandardAssets_ImageEffects_ScreenSpaceAmbientOcclusion_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::UnityStandardAssets.ImageEffects.SepiaTone), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_UnityStandardAssets_ImageEffects_SepiaTone_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::UnityStandardAssets.ImageEffects.SunShafts), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_UnityStandardAssets_ImageEffects_SunShafts_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::UnityStandardAssets.ImageEffects.Tonemapping), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_UnityStandardAssets_ImageEffects_Tonemapping_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::UnityStandardAssets.ImageEffects.Twirl), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_UnityStandardAssets_ImageEffects_Twirl_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::UnityStandardAssets.ImageEffects.VignetteAndChromaticAberration), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_UnityStandardAssets_ImageEffects_VignetteAndChromaticAberration_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly7bab937f240f4b3eb1090fbc7e25ce83::UnityStandardAssets.ImageEffects.Vortex), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly7bab937f240f4b3eb1090fbc7e25ce83_UnityStandardAssets_ImageEffects_Vortex_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly211d40e70b804a6887cb22caa5d0f790::Sirenix.OdinInspector.Editor.ColorPaletteManager), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly211d40e70b804a6887cb22caa5d0f790_Sirenix_OdinInspector_Editor_ColorPaletteManager_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly211d40e70b804a6887cb22caa5d0f790::Sirenix.OdinInspector.Editor.GeneralDrawerConfig), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly211d40e70b804a6887cb22caa5d0f790_Sirenix_OdinInspector_Editor_GeneralDrawerConfig_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly211d40e70b804a6887cb22caa5d0f790::Sirenix.OdinInspector.Editor.InspectorConfig), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly211d40e70b804a6887cb22caa5d0f790_Sirenix_OdinInspector_Editor_InspectorConfig_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly97d6cf9292cd44b6913f3f8ceba1f899::Sirenix.Serialization.GlobalSerializationConfig), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly97d6cf9292cd44b6913f3f8ceba1f899_Sirenix_Serialization_GlobalSerializationConfig_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
}
